### ISSUE TITLE
OS-level thread names confuse some tools

### ISSUE THREAD

**Issue by ongardie** [logcabin/logcabin#103]
```
<nhardt> i noticed that for top and production of a core file, the logcabin process is coming out as evloop
<nhardt> i think it has to do with that call to set the thread name in main()
<diego> yeah, i think that's right
<diego> i wonder if an extra clone() in Server/Main.cc would fix that
<diego> i do like the thread names being known to the OS sometimes
```
cc @nhardt

**Comment by ongardie** [comment]
I think spawning a new thread in main() fixes that, but reopen if it's still coming up somewhere.

**Comment by nhardt** [comment]
Seems like this is still an issue in some places. here's a few instances:

[root@scale-192-168-4-26 ~ ]# service logcabin start
Starting logcabin:                                         [  OK  ]
[root@scale-192-168-4-26 ~ ]# ps aux | grep logcabin | grep -v grep
root     14295  1.7  0.0 495320  2332 ?        Ssl  18:58   0:00 /usr/bin/logcabind --daemon --config /etc/logcabin.conf --log /var/log/logcabin.log --pidfile /var/run/logcabin.pid
[root@scale-192-168-4-26 ~ ]# top -b -n 1 | grep logcabin
[root@scale-192-168-4-26 ~ ]# top -b -n 1 | grep evloop
14295 root      20   0  483m 2336 1520 S  0.0  0.0   0:00.16 evloop
[root@scale-192-168-4-26 ~ ]# killall logcabind
logcabind: no process killed
[root@scale-192-168-4-26 ~ ]# pidof logcabind
14295
[root@scale-192-168-4-26 ~ ]# pidof evloop
[root@scale-192-168-4-26 ~ ]# killall evloop
[root@scale-192-168-4-26 ~ ]# killall evloop
evloop: no process killed
[root@scale-192-168-4-26 ~ ]# ps aux | grep logcabin | grep -v grep
[root@scale-192-168-4-26 ~ ]# top -b -n 1 | grep evloop

so, seems the method top and killall use to get the process name are confused by the thread rename.

tried pstree as well, this one gets evloop.
[root@scale-192-168-4-26 ~ ]# pstree
init─┬─acpid
....
     ├─evloop───6*[{evloop}]

**Comment by nhardt** [comment]
Oh, should have mentioned I'm on fdcd8de08bb8fd79e8784ed56f365817a2d34b94. (I have d4172886fb9c2b84d70c099e4dc9a280d1c289d2 "Close #103: OS-level thread names confuse some tools")

**Comment by ongardie** [comment]
ok, I'll just remove it then
