### ISSUE TITLE
potential child process deadlock

### ISSUE THREAD

**Issue by ongardie** [logcabin/logcabin#121]
@toddlipcon points out that if the parent process is holding a lock in another thread at the time a child process gets forked, that child won't be able to get the lock and could be blocked on it forever. LogCabin forks a child process to take a snapshot, and there aren't many locks on that path but:

- What would happen if the child process deadlocked? Ideally we'd detect this, kill it, increment a ServerStats counter, and eventually start a new child process. 
- What locks does the child process grab? Some that might not be obvious include those in glibc (such as malloc, which *should* use `pthread_atfork()` for this) and the lock on `stderr` in `Core/Debug.cc`.

**Comment by ongardie** [comment]
Before what would happen is the snapshotting process would wedge forever, and no more snapshots would be taken. 7c46a0d adds a new watchdog thread that runs in the parent process to watch the child, and kills it if it hasn't written anything for 10 seconds (by default).

I don't think the child process grabs many locks. The flockfile() in `Core/Debug.cc` is still a bit of a concern, but the child process doesn't usually log anything. Given that plus the watchdog plus the tiny window of vulnerability here, I'd prefer to wait and see if this is an actual problem before spending any time on it.

**Comment by nhardt** [comment]
This issue seemed interesting so I researched it a little. If there is an "actual" problem some day, looks like maybe pthread_atfork is worth looking at. The "Rationale" section seems to describe this situation exactly.

**Comment by ongardie** [comment]
@nhardt Yep, I think pthread_atfork is probably the way you're supposed to deal with this issue, although I guess you can get the same behavior if you are in control of all the fork calls. I used it in 83f19f5.

**Comment by nhardt** [comment]
What is the gain that comes from forking rather than just doing the IO in a separate thread?

**Comment by ongardie** [comment]
Not having to implement copy-on-write or any locking or reference counting for the state machine state (p54, 56).

**Comment by nhardt** [comment]
It looks like if a process forks that uses the log cabin client, the above mentioned deadlock can occur. Here's a stack:

[root@xxx ~ 19:16:31 ]# pstack [forked process of daemon with embedded logcabin client]
#0  0x00007fc8681d6264 in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007fc8681d1508 in _L_lock_854 () from /lib64/libpthread.so.0
#2  0x00007fc8681d13d7 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x0000000000d7c300 in __gthread_mutex_lock(pthread_mutex_t*) ()
#4  0x0000000000d7ecb6 in std::mutex::lock() ()
#5  0x0000000000d7f53a in std::lock_guard<std::mutex>::lock_guard(std::mutex&) ()
#6  0x0000000000e20778 in LogCabin::Core::Random::(anonymous namespace)::RandomState::reset() ()
#7  0x0000000000e209a0 in LogCabin::Core::Random::(anonymous namespace)::resetRandomState() ()
#8  0x00007fc867ee0c36 in fork () from /lib64/libc.so.6

Looking at possible solutions.

**Comment by ongardie** [comment]
> Looking at possible solutions.

In case anyone else stumbles on this and is wondering what happened, see PR #187.
