### ISSUE TITLE
ServerStats should be protected against its mutex

### ISSUE THREAD

**Issue by skypexu** [logcabin/logcabin#122]
```
diff --git a/Server/ServerStats.cc b/Server/ServerStats.cc
index 001ef3a..d4ce30b 100644
--- a/Server/ServerStats.cc
+++ b/Server/ServerStats.cc
@@ -30,7 +30,7 @@ namespace Server {
 
 ServerStats::Lock::Lock(ServerStats& wrapper)
     : wrapper(wrapper)
-    , lockGuard()
+    , lockGuard(wrapper.mutex)
 {
 }
```

**Comment by ongardie** [comment]
Nice one, thanks @skypexu! I just pushed the change to master.

It's too bad there's a default constructor on std::unique_lock that does nothing yet doesn't look at all suspicious. This is probably a good argument for using std::lock_guard instead wherever possible. The second commit here makes those changes throughout LogCabin.

Out of curiosity:

- How did you find this? Manual inspection or automated tools?
- Did this issue cause problems for you in testing?

**Comment by skypexu** [comment]
Hi,

I am learning raft, so I was reading logcabin code, and manually found 
the bug.

Regards,

**Comment by ongardie** [comment]
@skypexu: I see, well thanks for finding it :)

**Comment by ongardie** [comment]
@skypexu, see #97: some suboptimal code for it exists but has not been merged.
