### ISSUE TITLE
create logo

### ISSUE THREAD

**Issue by ongardie** [logcabin/logcabin#123]
LogCabin needs a logo, preferably before 1.0. Here's an image that might be useful, if we can get it to look more like a drawing. This is sitting on my desk for now, so I can take more images as needed if that'd help.

![cropped](https://cloud.githubusercontent.com/assets/463856/6987059/71633d62-d9f8-11e4-9132-9c31ca0afdc5.jpg)

I'm probably not the right person to do this. Anyone more artistically talented able to help?

**Comment by bch** [comment]
Couple more pix and some dimensions ?

**Comment by ongardie** [comment]
@bch I don't see how dimensions are important but here ya go:

![img_20150403_100126](https://cloud.githubusercontent.com/assets/463856/6987325/09d9fc8c-d9fb-11e4-9780-5f576770d490.jpg)
![img_20150403_101429](https://cloud.githubusercontent.com/assets/463856/6987326/09da4084-d9fb-11e4-975a-7150758d558f.jpg)
![img_20150403_110300](https://cloud.githubusercontent.com/assets/463856/6987329/09db816a-d9fb-11e4-80cb-cb5f851d96eb.jpg)
![img_20150403_110301](https://cloud.githubusercontent.com/assets/463856/6987328/09db4e2a-d9fb-11e4-8f91-aa12d90b03b1.jpg)
![img_20150403_120528](https://cloud.githubusercontent.com/assets/463856/6987330/09e187fe-d9fb-11e4-94fd-52c8e14e38c9.jpg)
![img_20150403_120553](https://cloud.githubusercontent.com/assets/463856/6987327/09dafb28-d9fb-11e4-8ca2-94a31b87c851.jpg)
![img_20150403_120616](https://cloud.githubusercontent.com/assets/463856/6987331/09e962d0-d9fb-11e4-9bea-758a57783951.jpg)
![img_20150403_120628](https://cloud.githubusercontent.com/assets/463856/6987334/09ef5762-d9fb-11e4-81e8-1330ae3f09bf.jpg)
![img_20150403_120644](https://cloud.githubusercontent.com/assets/463856/6987335/09efd408-d9fb-11e4-8324-23e540c58c98.jpg)
![img_20150403_120655](https://cloud.githubusercontent.com/assets/463856/6987333/09eee822-d9fb-11e4-8ed9-43cdc004a7f7.jpg)
![img_20150403_120712](https://cloud.githubusercontent.com/assets/463856/6987332/09ee56a0-d9fb-11e4-8c5e-9384629ca57a.jpg)
![img_20150403_120721](https://cloud.githubusercontent.com/assets/463856/6987336/09f3711c-d9fb-11e4-9e5d-1d53f76b0607.jpg)
![img_20150403_120748](https://cloud.githubusercontent.com/assets/463856/6987337/09f78658-d9fb-11e4-8574-b9e74de73fd7.jpg)
![img_20150403_120752](https://cloud.githubusercontent.com/assets/463856/6987339/0a007b14-d9fb-11e4-9a0a-16272efa3ed6.jpg)
![img_20150403_120756](https://cloud.githubusercontent.com/assets/463856/6987340/0a02d224-d9fb-11e4-9d2e-d7b892c841a9.jpg)
![img_20150403_120802](https://cloud.githubusercontent.com/assets/463856/6987338/09fe1810-d9fb-11e4-9b56-13822dc05633.jpg)
![img_20150403_120814](https://cloud.githubusercontent.com/assets/463856/6987341/0a03cbe8-d9fb-11e4-9161-810680d68214.jpg)
![img_20150403_120817](https://cloud.githubusercontent.com/assets/463856/6987342/0a05bb88-d9fb-11e4-823b-1eca67ae3735.jpg)
![img_20150403_120827](https://cloud.githubusercontent.com/assets/463856/6987343/0a091c56-d9fb-11e4-8bac-809d7b5e7aef.jpg)
![img_20150403_120829](https://cloud.githubusercontent.com/assets/463856/6987344/0a0e1f44-d9fb-11e4-83ed-060a21005f6b.jpg)
![img_20150403_120830](https://cloud.githubusercontent.com/assets/463856/6987346/0a1706b8-d9fb-11e4-8eab-a70687bc253a.jpg)
![img_20150403_120834](https://cloud.githubusercontent.com/assets/463856/6987347/0a175a28-d9fb-11e4-85a1-977e4f7095f6.jpg)
![img_20150403_120836](https://cloud.githubusercontent.com/assets/463856/6987348/0a1767fc-d9fb-11e4-9c7e-f2880d34c446.jpg)
![img_20150403_120838](https://cloud.githubusercontent.com/assets/463856/6987349/0a197d6c-d9fb-11e4-9cb5-f6df4a17f848.jpg)
![img_20150403_120840](https://cloud.githubusercontent.com/assets/463856/6987345/0a168d8c-d9fb-11e4-9c58-a0d9a20e9352.jpg)
![img_20150403_120854](https://cloud.githubusercontent.com/assets/463856/6987350/0a1d048c-d9fb-11e4-9760-198ca8c248fa.jpg)

**Comment by ongardie** [comment]
@bch, are you trying this? It sounds like 14BlackPoppies on twitter might be willing also: https://twitter.com/14BlackPoppies/status/584075100590211072

**Comment by bch** [comment]
Hi -- ya - I was going to try a 3d cad model and see what happens --
don't let my interest stop anybody else though...

-bch

**Comment by ongardie** [comment]
Hope y'all like what I came up with :)

![logo](https://raw.githubusercontent.com/logcabin/logcabin/master/logo/500px.png)

Of course, I'd be happy to switch to something better if someone with more artistic ability wants to work on this (probably best to open a new issue at that point).
