### ISSUE TITLE
running tests

### ISSUE THREAD

**Issue by krizajb** [logcabin/logcabin#128]
Hey, I followed your build instructions and tried to fire tests but without any success. Some of them fail but many of them crash because of a common reason which is: Missing fields in protocol buffer of type LogCabin.Server.SnapshotMetadata.Header: configuration.prev_configuration.servers[0].addresses. 

I am fairly new to protobuf, but as seen the Configuration included in SnapshotMetadata.Header requires prev_configuration to be set. I tried tracking down where the header could be setting/not setting the property but didn't manage to do so. So after few hours, I decided to bring that matter up here to maybe also help someone else. Do tests require some kind of configuration as well?

With VERBOSE env set to 1 I was able to track down some of the test cases crashing with the reason mentioned above:
TEST_F(ServerStateMachineTest, applyThreadMain_exiting_TimingSensitive)
TEST_F(ServerStateMachineTest, takeSnapshot)
TEST_F(ServerRaftConsensusTest, init_withsnapshot)
TEST_F(ServerRaftConsensusTest, getNextEntry_snapshot)
TEST_F(ServerRaftConsensusTest, getSnapshotStats)
...

Thank you.

**Comment by ongardie** [comment]
Hey @krizajb, thanks for the bug report. I run the unit tests on my machine after every commit (as does Travis CI), and I'm not seeing this problem. That doesn't mean it's not a real issue, but I'd like to reproduce it on my end before trying to fix it. There must be something different about your machine than mine, so more information on what you're using would help.

- Which commit of logcabin are you using? I'm on the latest master, 7c46a0d.
- What version of protobuf do you have? I'm on 2.6.1.
- Which distro and compiler version, just in case that matters? I'm on Debian Jessie using gcc-4.4.

By the way, as a workaround, you can probably just set that field to optional in the .proto file.

**Comment by krizajb** [comment]
Hi, hope you mean before every commit :)

Version information:
- Same commit (latest) version as yours.
- protobuf 2.3.0-9 (will try updating it and see how it goes)
- CentOS 6.6, gcc 4.4.7

The workaround didn't work, seems other field required isn't set, pasting core dump. Tests before this one pass.

[ RUN      ] ServerStateMachineTest.applyThreadMain_exiting_TimingSensitive
2015-04-20 07:46:11.737035 Core/ProtoBuf.cc:167 in serialize() ERROR[5914:thread 1]: Missing fields in protocol buffer of type LogCabin.Server.SnapshotMetadata.Header: configuration.prev_configuration.servers[0].addresses (have last_included_index: 1
configuration {
  prev_configuration {
    servers {
      server_id: 1
    }
  }
}
configuration_index: 1
last_included_term: 1
last_cluster_time: 0
last_included_index: 1
configuration {
  prev_configuration {
    servers {
      server_id: 1
    }
  }
}
configuration_index: 1
last_included_term: 1
last_cluster_time: 0
configuration.prev_configuration.servers[0].addresses: UNDEFINED
) Exiting...
Aborted (core dumped)

**Comment by ongardie** [comment]
Cool, I just updated the README accordingly in 05e0c17. I don't see any reason to use protobuf < v2.5 at this point, so let's not worry too much about this. I think most of the issues you were having centered around the ProtoBuf text format, which isn't used much outside of log messages and tests. There's probably some cleanup that we could do to make it pass with 2.3, but I vote for moving on with our lives :)

**Comment by ongardie** [comment]
> hope you mean before every commit :)

Yes, I guess you're right. I use the pre-commit hook included at hooks/pre-commit in the repo. So it's after I type git commit but before the actual commit occurs.
