### ISSUE TITLE
Possible missing boundary-check code

### ISSUE THREAD

**Issue by skypexu** [logcabin/logcabin#149]
```
diff --git a/Storage/SegmentedLog.cc b/Storage/SegmentedLog.cc
index ca35b9c..9c73ae7 100644
--- a/Storage/SegmentedLog.cc
+++ b/Storage/SegmentedLog.cc
@@ -597,7 +597,8 @@ SegmentedLog::truncateSuffix(uint64_t newEndIndex)
     { // Check if the open segment has some entries we need. If so,
       // just truncate that segment, open a new one, and return.
         Segment& openSegment = getOpenSegment();
-        if (newEndIndex >= openSegment.startIndex) {
+        if (newEndIndex >= openSegment.startIndex &&
+            openSegment.endIndex > newEndIndex) {
             // Update in-memory segment
             uint64_t i = newEndIndex + 1 - openSegment.startIndex;
             openSegment.bytes = openSegment.entries.at(i).offset;
diff --git a/gtest b/gtest
index c6d1811..2809135 160000
```

Without these additional code, a large newEndIndex can cause non-existing record memory to
be referenced.

**Comment by ongardie** [comment]
Thanks again for the extra eyes, @skypexu.

Hmm, I think this is covered by:
```
 592     if (newEndIndex >= getLastLogIndex())
 593         return;
```
where getLastLogIndex expands to:
```
 525         return getOpenSegment().endIndex;
```
So we have the constraint that `(newEndIndex >= openSegment.endIndex) == false` on this path already.

Even if that weren't true, I think the worst case is that this would crash with an uncaught out of bounds exception at line 603:
```
 602             uint64_t i = newEndIndex + 1 - openSegment.startIndex;
 603             openSegment.bytes = openSegment.entries.at(i).offset;
```

**Comment by skypexu** [comment]
On 2015年05月30日 05:57, Diego Ongaro wrote:
>
> Thanks again for the extra eyes, @skypexu <https://github.com/skypexu>.
>
> Hmm, I think this is covered by:
>
> |  592     if (newEndIndex >= getLastLogIndex())
> |
|You are right, I have not caught this sentence, I think the PR can be 
closed.

|

**Comment by ongardie** [comment]
Alright, well, thanks @skypexu, hope you keep reporting more in the future :)
