### ISSUE TITLE
“abort” in ControlService::snapshotInhibitSet

### ISSUE THREAD

**Issue by jujing** [logcabin/logcabin#192]
Function ControlService::snapshotInhibitSet  in Server/ControlService.cc
The variable “abort” is initialized as false. 
And no other place set it true. 
So in line 248, it is always false, and never do stopTakingSnapshot.
Whether is should be initialized as true here?
Thanks.

**Comment by ongardie** [comment]
Good find. I think it should be initialized as true. What's supposed to happen is documented here: https://github.com/logcabin/logcabin/blob/v1.1.0/Protocol/ServerControl.proto#L226
