### ISSUE TITLE
When pidfile is invalid

### ISSUE THREAD

**Issue by jujing** [logcabin/logcabin#193]
In file Server/Main.cc, in function writePid of PidFile. 
When the FILE* file is NULL, it would be pass to fwrite. 
I think use PANIC instead of ERROR (in line 203) when we found fill is NULL would be better.

**Comment by ongardie** [comment]
Agreed. "ERROR" should be "PANIC" on https://github.com/logcabin/logcabin/blob/9704f012fb8bd6305a1e75b0a12c13377252cd98/Server/Main.cc#L203
