### ISSUE TITLE
cmake

### ISSUE THREAD

**Issue by tigerzhang** [logcabin/logcabin#224]
I wonder if it's possible to switch the build system from SCons to CMake. CMake is much popular currently.

We are working on a project based on the code base of logcabin, and we have switched to CMake in our project. We can create a PR.

**Comment by ongardie** [comment]
Hey @TigerZhang,

I think CMake would be a welcome change, thanks! I've never really gotten to like SCons and have heard better things about CMake.

Is it possible to do this in two phases, first adding CMake side-by-side with SCons, then removing Scons? This would give people a chance to try out and transition over to CMake before pulling the plug on SCons.

**Comment by ongardie** [comment]
linking to PR #227 ("support cmake compiling")

**Comment by TigerZhang** [comment]
@ongardie I'm glad to review the PR #227

**Comment by ongardie** [comment]
Thanks @tigerzhang, that'd be helpful, since I'm new to cmake.

cc @johnzeng
