### ISSUE TITLE
rdtsc test case accuracy on x86_64.

### ISSUE THREAD

**Issue by sowani** [logcabin/logcabin#225]
Hi,

I was running the logcabin test suite on my machine and one of the rdtsc test case (rdtsc_progressTimingSensitive, EXPECT_LT(a * 1000 * 1000, b);) fails for me consistently where timebase ticks are compared after a sleep delay (1000 microsec). Though the variance in the tick values before and after was very very small, but indeed it was there.

While discussing this with the experts, they suggested me that on older intel chips, rdtsc rate is variable with CPU clock (which is not the case with latest Intel chips) and advised me to use "isync" instruction before calling rdtsc to ensure synchronized instruction execution order.

Do you think the test case should be modified to make it more resilient for this kind of scenario observed in my case? If okay, I will create a pull request for this change with updated code.

Thanks,
Atul.

**Comment by ongardie** [comment]
Hey @sowani, sorry for the long delay. Why'd you close this? It seems like a valid complaint to me.

How about changing:

    EXPECT_LT(a + 1000 * 1000, b);

to:

    EXPECT_LT(a + 1000 * 900, b);

Would that be good enough for most reasonable CPUs?

**Comment by sowani** [comment]
@ongardie Thanks for responding and re-opening this issue. I closed it as I didn't get any response and did not hope to get any, so your response was indeed welcome!

I tried the changes you suggested and obtained a few results. The test fails even with "900". Typical values are as follows:
Run 1:
build/Core/TimeTest.cc:263: Failure
Expected: (a * 1000 * 900) < (b), actual: 876232819846779456 vs 7871584397350686
Run 2:
build/Core/TimeTest.cc:263: Failure
Expected: (a * 1000 * 900) < (b), actual: 896691502889979456 vs 7871607129220134
Run 3:
build/Core/TimeTest.cc:263: Failure
Expected: (a * 1000 * 900) < (b), actual: 977104264638579456 vs 7871696476734194

Thanks,
Atul.

**Comment by sowani** [comment]
With some trial-and-error, I found that the multiplication factor of 500 works okay on ppc64le (a + 1000 * 500).

**Comment by ongardie** [comment]
I'm confused. What CPU produced the runs you showed [above](https://github.com/logcabin/logcabin/issues/225#issuecomment-277163867)? I don't even know how to read that either, is it `a vs b` or `a * 100 * 900 vs b`? I still don't get why you'd multiply `a` by anything. In any case, those look off by much more than 1000 * 500.

**Comment by sowani** [comment]
It is "a *+*" - there was a typo in my original posting. It's not "a * 1000
* 500" but "a + 1000 * 500". Sorry for the typo.

**Comment by ongardie** [comment]
Closed by #229.

**Comment by sowani** [comment]
Thank you very much @ongardie !
