### ISSUE TITLE
New PR: logcabin ported to IBM Power8/LE (ppc64le) platform.

### ISSUE THREAD

**Issue by asowani** [logcabin/logcabin#228]
Hi,

This is just a heads-up message. I have successfully ported logcabin to IBM's ppc64le (Power8/LE) platform. For this a change is required in Core/Time.h file. Also, there is a slight change required in one of the test cases in Core/TimeTest.cc file. I will create a pull request for this change shortly.

Thanks,
Atul.

**Comment by asowani** [comment]
I have created corresponding PR at https://github.com/logcabin/logcabin/pull/229

Best regards,
Atul.

**Comment by ongardie** [comment]
Thanks. I'm closing this issue as it's pretty well-tracked in the PR #229 now.
