### ISSUE TITLE
After executing, "Reconfigure", leader still not syncing up with the followers

### ISSUE THREAD

**Issue by zishancrusader** [logcabin/logcabin#85]
I tried building and starting LogCabin servers on my machines as described in the README. The conf contained 2 servers and their exact IP addresses for eth.

Steps followed:
1. created a logcabin.conf in the working directory.

2. executed "./build/LogCabin --bootstrap -i 1 -c logcabin.conf" from one of the servers (the first one in the conf).

3. executed "./build/LogCabin -i 1 -c logcabin.conf"
executed  "./build/LogCabin -i 2 -c logcabin.conf"

from the respective servers.

4. Executed "./build/Examples/Reconfigure -c <ip_addr1> <ip_addr2>" on the leader. This command executed successfully.

5. I believe, as per the README, the follower should have received the config, come out of the idling wait and start participating. But this did not happen here. The leader reached upto commit_index 31 and on the stats on follower, the index was still 0.

Even when I killed the leader, no-relection happened and bringing back the old leader made it the leader again.

Am I missing something?

**Comment by ongardie** [comment]
Hey Zishan,

It sounds like Reconfigure didn't do its job. #72 and #73 are open to improve on its usability, but meanwhile, is that the full command you used for it? You should be listing both of the IPs for the servers, space-separated, as command line arguments. Please paste the full command you ran and the output from it.

Two more things might be helpful: your commit hash (git show), and a copy of the ServerStats output from either of the servers (they'll print these in the logs every minute by default, or send a SIGUSR1).The servers' current configurations is buried somewhere in ServerStats.

Finally, you probably know this already, but for anything interesting, you'll need 3 servers. With a 2-server cluster, both servers have to be available to make progress, but 3-server clusters only need 2 servers up.

**Comment by zishancrusader** [comment]
Hey Diego,

Thanks for the prompt reply. I was testing if I can use the Logcabin implementation of RAFT in my application. So I just tried it on two servers.

Answers to a few questions you've asked:
1. I just posted the execution steps. For Reconfigure, I did use the full command, with addresses of the nodes separated by spaces. Here, the full command:

./build/Examples/Reconfigure -c 10.10.92.1:61023 10.10.92.4:61023

Configuration 1:
- 1: 10.10.92.1:61023

Reconfiguration OK
Configuration 4:
- 1: 10.10.92.4:61023

2. Server stats:
From the leader (where --bootstrap was executed once)

1421829828.650869 Server/ServerStats.cc:84 in handleTimerEvent() NOTICE[1:evloop]: Periodic dump of ServerStats:
server_id: 1
address: "10.10.92.1:61023"
start_at: 1421829828650507483
end_at: 1421829828650616936
raft {
  current_term: 2
  state: LEADER
  commit_index: 2
  last_log_index: 2
  leader_id: 1
  voted_for: 1
  start_election_at: 9223372036854775807
  withhold_votes_until: 9223372036854775807
  last_snapshot_index: 0
  last_snapshot_bytes: 0
  log_start_index: 1
  log_bytes: 34
  peer {
    server_id: 1
    old_member: true
    new_member: false
    staging_member: false
    last_synced_index: 2
  }
}

1421829867.430360 Server/RaftConsensus.cc:539 in setConfiguration() NOTICE[1:ClientService(7)]: Activating configuration 3:
prev_configuration {
  servers {
    server_id: 1
    address: "10.10.92.1:61023"
  }
}
next_configuration {
  servers {
    server_id: 1
    address: "10.10.92.4:61023"
  }
}


From the follower (which did not participate after Reconfigure)
1421829976.264727 Server/ServerStats.cc:84 in handleTimerEvent() NOTICE[2:evloop]: Periodic dump of ServerStats:
server_id: 2
address: "10.10.92.4:61023"
start_at: 1421829976264685795
end_at: 1421829976264704375
raft {
  current_term: 0
  state: FOLLOWER
  commit_index: 0
  last_log_index: 0
  leader_id: 0
  voted_for: 0
  start_election_at: 1421829976361089665
  withhold_votes_until: -7802015298503630469
  last_snapshot_index: 0
  last_snapshot_bytes: 0
  log_start_index: 1
  log_bytes: 0
  peer {
    server_id: 2
    old_member: false
    new_member: false
    staging_member: false
    last_synced_index: 0
  }
}


Also, when I executed Reconfigure, I saw this on the leader:
Activating configuration 3:
prev_configuration {
  servers {
    server_id: 1
    address: "10.10.92.1:61023"
  }
}
next_configuration {
  servers {
    server_id: 1
    address: "10.10.92.4:61023"
  }
}

What confused me is  why is the server_id = 1 here? It should be 2 AFAIK. While debugging, I saw it being to 1:
(gdb) p it->first
$3 = 1
(gdb) p it->second
$4 = "10.10.92.4:61023"

And,

(gdb) p newConfiguration.end()
$2 = {first = 6929920, second = <error reading variable: Cannot access memory at address 0x9>}

3. Current repo
 git show
commit d737edf9f8c07cba57608bbc5601e87076c710e9
Author: Diego Ongaro <dongaro@scalecomputing.com>
Date:   Thu Jan 15 22:18:07 2015 -0800

Let me know if you need anything else.
Thanks!

**Comment by ongardie** [comment]
Thanks for the additional info. The short answer is, I think you want:

    ./build/Examples/Reconfigure -c 10.10.92.1:61023 10.10.92.1:61023 10.10.92.4:61023

instead of:

    ./build/Examples/Reconfigure -c 10.10.92.1:61023 10.10.92.4:61023

That is, "find the cluster at 10.10.92.1, and change its configuration to be 10.10.92.1 and 10.10.92.4" rather than  "find the cluster at 10.10.92.1, and change its configuration to be 10.10.92.4".

The extra-confusing behavior you're seeing is due to #73. It seems that bug makes either the leader or the server with ID 1 take the first server listed in Reconfigure as its own address. I hope to get to that one soon.

**Comment by zishancrusader** [comment]
Hey Diego,

Thanks for the help. Using the Reconfigure command the way you have specified worked for me.
Although, I think this should be reflected in the README. And with this in place, I didn't see the confusing behavior I mentioned in the previous comment. 

Thanks for your help!

**Comment by ongardie** [comment]
Cool, glad things are working for you now. I'll just reopen this issue as a reminder to update the README.
