### ISSUE TITLE
make client session timeout use monotonic clock

### ISSUE THREAD

**Issue by ongardie** [logcabin/logcabin#90]
Scale has a test where they mess with the system clock on the servers, and this needlessly PANICs clients with SESSION_EXPIRED errors. It'd be better to use a clock that ticks based on time passing on the leader but doesn't pretend to follow the Unix epoch.

**Comment by ongardie** [comment]
There's an added bonus to this: if the network is out entirely, time won't pass.

**Comment by ongardie** [comment]
@nhardt, I think this is fixed in branch "issue-90". Can you run it through that regression test before I merge it into master?

**Comment by ongardie** [comment]
test passed, thanks @nhardt

**Comment by nhardt** [comment]
no problem, thank you!
